# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6da03f8ca2ab07e99ace0fcfcc7f3302152bc4f4934c9710b150b10015302ec1fb7f3a28a3e5ddd10e8a476300a6188381e14374f216977e644b436e06070b45

test:
  secret_key_base: bd91d46d047140b3a94e3463919a3d0bf96be7fb238e851782af4aa3c9bc69e6858cc79468c2ed0e8a4600487ae50b298e3b37b2937ab75f11242a6d612b6ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
